### PR TITLE
issue #10

### PR DESCRIPTION
**Pull request by sksDonni**
Hello,

I have tried improving the UI of the login page. If you wish to see some improvements, I am ready to get the UI done as per your inspiration. 
Note- Since the Jinja text were a disturbance while working, I started the class = "container trans" once again. I also created a new login.css file for the stylesheet keeping in mind the seperation of concerns.
I have commented your code in the login.html file after the closing tags.

It was a pleasure contributing!!

### CODE REVIEW

**Comment by ektaarora3501** [comment]
Hey .. Thanks for Contributing. Can you share the Screen shots of UI updates. Easy for me to review

**Comment by sksDonni** [comment]
Sure!
1.
Screenshot (24)

**Comment by ektaarora3501** [comment]
hi, The form looks good... But Do remove the logo as this is the unofficial site.  Also the backend part is commented out, do integrate it accordingly

**Comment by sksDonni** [comment]
Ya, sure will be done!
Any other replacement for the logo on your mind? Will be easy for me.

**Comment by ektaarora3501** [comment]
You can keep a general login logo ..

**Comment by sksDonni** [comment]
Good evening there!

I have replaced the logo with a general icon as specified. I have also included the screenshots of the output in the postscript.
It was a pleasure contributing.

P.S - 
Screenshot (25)

**Comment by ektaarora3501** [comment]
Thats great..

**Pull request merged**
